### ISSUE TITLE
视频流播放界面

### ISSUE THREAD

**Issue by wangdemon** [yangjiechina/GB28181_Stress_Tools#7]
![img](https://user-images.githubusercontent.com/20681339/190096379-22d5580d-7b69-4471-9d12-6a76262d570a.png)
上图所示界面，是哪里的，项目中，好像没有该界面

**Comment by ydajiang** [comment]
> ![img](https://user-images.githubusercontent.com/20681339/190096379-22d5580d-7b69-4471-9d12-6a76262d570a.png) 上图所示界面，是哪里的，项目中，好像没有该界面

QQ群文件里面有

**Comment by wangdemon** [comment]
好的，感谢大佬。
我用项目注册其他的开源服务器，有的成功，有的失败，可能是什么原因导致的？
